// <auto-generated />
using System;
using FlowHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FlowHub.Persistence.Migrations
{
    [DbContext(typeof(FlowHubDbContext))]
    [Migration("20260610185140_0010_AddClassifierTrace")]
    partial class _0010_AddClassifierTrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowHub.Persistence.Entities.CaptureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<string>("EnrichmentDescription")
                        .HasColumnType("text");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("MatchedSkill")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("VikunjaProject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Captures_CreatedAt_DESC");

                    b.HasIndex("MatchedSkill")
                        .HasDatabaseName("IX_Captures_MatchedSkill");

                    b.HasIndex("Stage")
                        .HasDatabaseName("IX_Captures_Stage");

                    b.ToTable("Captures", (string)null);
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.ChannelEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Name");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.IntegrationEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastWriteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastWriteDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Name");

                    b.ToTable("Integrations", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Wallabag",
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Vikunja",
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Paperless",
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Authentik",
                            Status = "Healthy"
                        });
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.IntegrationHealthSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrationName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("SampledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationName", "SampledAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_IntegrationHealthSamples_IntegrationName_SampledAt_DESC");

                    b.ToTable("IntegrationHealthSamples", (string)null);
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.SkillEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoutedToday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Name");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Books",
                            RoutedToday = 0,
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Movies",
                            RoutedToday = 0,
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Articles",
                            RoutedToday = 0,
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Quotes",
                            RoutedToday = 0,
                            Status = "Degraded"
                        },
                        new
                        {
                            Name = "Knowledge",
                            RoutedToday = 0,
                            Status = "Healthy"
                        },
                        new
                        {
                            Name = "Belege",
                            RoutedToday = 0,
                            Status = "Healthy"
                        });
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.SkillRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CaptureId");

                    b.HasIndex("SkillName");

                    b.ToTable("SkillRuns", (string)null);
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("CaptureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CaptureId", "Value");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.CaptureEntity", b =>
                {
                    b.OwnsOne("FlowHub.Persistence.Entities.AttachmentEntity", "Attachment", b1 =>
                        {
                            b1.Property<Guid>("CaptureEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Attachment_ContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Attachment_FileName");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Attachment_RelativePath");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("Attachment_SizeBytes");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Attachment_UploadedAt");

                            b1.HasKey("CaptureEntityId");

                            b1.ToTable("Captures");

                            b1.WithOwner()
                                .HasForeignKey("CaptureEntityId");
                        });

                    b.OwnsOne("FlowHub.Persistence.Entities.ClassifierTraceOwned", "ClassifierTrace", b1 =>
                        {
                            b1.Property<Guid>("CaptureEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("ClassifierTrace_CompletionTokens");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("ClassifierTrace_Kind");

                            b1.Property<int>("LatencyMs")
                                .HasColumnType("integer")
                                .HasColumnName("ClassifierTrace_LatencyMs");

                            b1.Property<string>("Model")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ClassifierTrace_Model");

                            b1.Property<int?>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("ClassifierTrace_PromptTokens");

                            b1.Property<string>("Provider")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("ClassifierTrace_Provider");

                            b1.HasKey("CaptureEntityId");

                            b1.ToTable("Captures");

                            b1.WithOwner()
                                .HasForeignKey("CaptureEntityId");
                        });

                    b.Navigation("Attachment");

                    b.Navigation("ClassifierTrace");
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.IntegrationHealthSampleEntity", b =>
                {
                    b.HasOne("FlowHub.Persistence.Entities.IntegrationEntity", "Integration")
                        .WithMany("Samples")
                        .HasForeignKey("IntegrationName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.SkillRunEntity", b =>
                {
                    b.HasOne("FlowHub.Persistence.Entities.CaptureEntity", "Capture")
                        .WithMany()
                        .HasForeignKey("CaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowHub.Persistence.Entities.SkillEntity", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capture");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.TagEntity", b =>
                {
                    b.HasOne("FlowHub.Persistence.Entities.CaptureEntity", "Capture")
                        .WithMany("Tags")
                        .HasForeignKey("CaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capture");
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.CaptureEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FlowHub.Persistence.Entities.IntegrationEntity", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
