#!/usr/bin/env bash
# demo/vikunja/bootstrap.sh — one-shot provisioning for the demo Vikunja instance.
#
# Idempotent: safe to re-run on every `docker compose up` (the Vikunja sqlite volume
# persists across restarts). It:
#   1. waits for the Vikunja API to come up,
#   2. registers the demo user (ignored if it already exists),
#   3. logs in with a long-lived token (jwtttllong default = 30 days),
#   4. ensures a single "Inbox" project exists,
#   5. ensures a public, read-only link-share on that project (no login needed),
#   6. writes /bootstrap/vikunja.env — sourced by flowhub.web (to activate the
#      Vikunja skill) and by the reset sidecar (to clear tasks each cycle).
#
# The written token is a normal user JWT; FlowHub's VikunjaSkillIntegration sends it
# as `Authorization: Bearer <token>`, which Vikunja accepts for task creation.

set -euo pipefail

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { echo "[$(ts)] vikunja-bootstrap: $*"; }

API="${VIKUNJA_API_URL:-http://vikunja:3456/api/v1}"
PUBLIC_URL="${VIKUNJA_PUBLIC_URL:-https://vikunja.demo.flowhub.freaxnx01.ch}"
DEMO_USER="${VIKUNJA_DEMO_USER:-flowhub}"
DEMO_PASS="${VIKUNJA_DEMO_PASSWORD:-flowhub-demo}"
DEMO_EMAIL="${VIKUNJA_DEMO_EMAIL:-flowhub-demo@example.invalid}"
PROJECT_TITLE="${VIKUNJA_DEMO_PROJECT:-Inbox}"
OUT="${BOOTSTRAP_OUT:-/bootstrap/vikunja.env}"

# 1. Wait for the API (the unified image serves API + frontend on :3456).
log "waiting for ${API}/info ..."
ready=""
for _ in $(seq 1 90); do
  if curl -fsS "${API}/info" >/dev/null 2>&1; then ready=1; break; fi
  sleep 2
done
[ -n "${ready}" ] || { log "ERROR: Vikunja did not become ready"; exit 1; }
log "Vikunja is up"

# 2. Register the demo user (idempotent — a 400 means it already exists).
code=$(curl -sS -o /tmp/register.json -w '%{http_code}' \
  -X POST "${API}/register" -H 'Content-Type: application/json' \
  -d "{\"username\":\"${DEMO_USER}\",\"email\":\"${DEMO_EMAIL}\",\"password\":\"${DEMO_PASS}\"}" || true)
case "${code}" in
  200|201) log "registered demo user '${DEMO_USER}'" ;;
  *)       log "register returned ${code} (user likely already exists) — continuing" ;;
esac

# 3. Log in with a long-lived token.
curl -fsS -X POST "${API}/login" -H 'Content-Type: application/json' \
  -d "{\"username\":\"${DEMO_USER}\",\"password\":\"${DEMO_PASS}\",\"long_token\":true}" \
  -o /tmp/login.json
TOKEN=$(jq -r '.token // empty' /tmp/login.json)
[ -n "${TOKEN}" ] || { log "ERROR: login failed"; cat /tmp/login.json; exit 1; }
AUTH="Authorization: Bearer ${TOKEN}"
log "logged in"

# Helper: ensure a project exists by title (reuse, else create); echoes its id.
ensure_project() {
  local title="$1" pid
  pid=$(curl -fsS "${API}/projects" -H "${AUTH}" \
    | jq -r --arg t "${title}" 'map(select(.title==$t)) | (.[0].id // empty)')
  if [ -z "${pid}" ]; then
    pid=$(curl -fsS -X PUT "${API}/projects" -H "${AUTH}" -H 'Content-Type: application/json' \
      -d "{\"title\":\"${title}\"}" | jq -r '.id')
  fi
  echo "${pid}"
}

# Helper: ensure a public, read-only link-share (right=0 read, sharing_type=1 no
# password) on a project; echoes the share hash.
ensure_share() {
  local pid="$1" h
  h=$(curl -fsS "${API}/projects/${pid}/shares" -H "${AUTH}" | jq -r '(.[0].hash // empty)')
  if [ -z "${h}" ]; then
    h=$(curl -fsS -X PUT "${API}/projects/${pid}/shares" -H "${AUTH}" -H 'Content-Type: application/json' \
      -d '{"right":0,"sharing_type":1}' | jq -r '.hash // empty')
  fi
  echo "${h}"
}

# 4. Inbox — the fallback project that "todo:" + uncategorised Vikunja captures land in.
PID=$(ensure_project "${PROJECT_TITLE}")
[ -n "${PID}" ] && [ "${PID}" != "null" ] || { log "ERROR: could not resolve Inbox project id"; exit 1; }
HASH=$(ensure_share "${PID}")
[ -n "${HASH}" ] || { log "ERROR: could not resolve Inbox share hash"; exit 1; }
SHARE_URL="${PUBLIC_URL%/}/share/${HASH}/auth"
log "Inbox project id=${PID}"

# 5. Zitate — quote captures route here (project name matches the ZitateEnricher
#    bucket), so the classifier picks 'Zitate' and the enricher adds author/context.
ZITATE_TITLE="${VIKUNJA_ZITATE_PROJECT:-Zitate}"
ZID=$(ensure_project "${ZITATE_TITLE}")
[ -n "${ZID}" ] && [ "${ZID}" != "null" ] || { log "ERROR: could not resolve Zitate project id"; exit 1; }
ZHASH=$(ensure_share "${ZID}")
[ -n "${ZHASH}" ] || { log "ERROR: could not resolve Zitate share hash"; exit 1; }
ZITATE_SHARE_URL="${PUBLIC_URL%/}/share/${ZHASH}/auth"
log "Zitate project id=${ZID}"

# 6. Write the env file consumed by flowhub.web (skill activation) and the reset sidecar.
#    BaseUrl is the host root — FlowHub appends /api/v1/projects/{id}/tasks itself.
mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
# Generated by demo/vikunja/bootstrap.sh — do not edit by hand.
Skills__Vikunja__BaseUrl=${API%/api/v1}
Skills__Vikunja__ApiToken=${TOKEN}
Skills__Vikunja__FallbackProject=${PROJECT_TITLE}
Skills__Vikunja__FallbackProjectId=${PID}
Demo__Vikunja__ShareUrl=${SHARE_URL}
Demo__Vikunja__ZitateShareUrl=${ZITATE_SHARE_URL}
VIKUNJA_API_URL=${API}
VIKUNJA_PROJECT_ID=${PID}
VIKUNJA_ZITATE_PROJECT_ID=${ZID}
VIKUNJA_TOKEN=${TOKEN}
EOF
log "wrote ${OUT} (inbox=${PID}, zitate=${ZID})"
log "done"
