using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FlowHub.AI;

/// <summary>
/// Schema-driven response shape consumed by MEAI's structured-output pipeline.
/// Attributes drive the JSON schema generated by MEAI: Description ↦ schema "description",
/// AllowedValues ↦ schema "enum". Both Anthropic (tool-use) and OpenRouter (response_format)
/// honour the generated schema.
/// </summary>
internal sealed record AiClassificationResponse(
    [property: Description("1–5 short lowercase tags describing the snippet")]
    string[] Tags,

    [property: Description("Wallabag, Vikunja, or empty string for none")]
    [property: AllowedValues("Wallabag", "Vikunja", "")]
    string MatchedSkill,

    [property: Description("3–8 word title or null if content is too short")]
    string? Title);
