#!/usr/bin/env bash
# demo/wallabag/bootstrap.sh — provision the demo Wallabag instance.
# Waits for the API, verifies the OAuth client + demo user yield a token (fail fast),
# and writes /bootstrap/wallabag.env with the client credentials + demo user login.
# The FlowHub Wallabag skill performs the password grant itself at runtime (tokens
# expire hourly), so only credentials are stored here — not a token.
#
# NOTE: the OAuth client (WALLABAG_CLIENT_ID/SECRET) is created once by the
# flowhub.wallabag-client init (which runs before this service) and written to
# /bootstrap/wallabag-client.env — see demo/docker-compose.yml. This script sources
# that file to obtain the credentials, then only verifies + records them.

set -euo pipefail

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { echo "[$(ts)] wallabag-bootstrap: $*"; }

API="${WALLABAG_API_URL:-http://wallabag:80}"
USER="${WALLABAG_DEMO_USER:-flowhub}"
PASS="${WALLABAG_DEMO_PASSWORD:-flowhub-demo}"
OUT="${BOOTSTRAP_OUT:-/bootstrap/wallabag.env}"

# OAuth client credentials are provisioned by flowhub.wallabag-client.
CLIENT_ENV="${WALLABAG_CLIENT_ENV:-/bootstrap/wallabag-client.env}"
if [ -f "${CLIENT_ENV}" ]; then
  set -a; . "${CLIENT_ENV}"; set +a
fi
CLIENT_ID="${WALLABAG_CLIENT_ID:?WALLABAG_CLIENT_ID required (from ${CLIENT_ENV})}"
CLIENT_SECRET="${WALLABAG_CLIENT_SECRET:?WALLABAG_CLIENT_SECRET required (from ${CLIENT_ENV})}"

log "waiting for ${API}/api/info ..."
ready=""
for _ in $(seq 1 120); do
  if curl -fsS "${API}/api/info" >/dev/null 2>&1; then ready=1; break; fi
  sleep 3
done
[ -n "${ready}" ] || { log "ERROR: wallabag did not become ready"; exit 1; }
log "wallabag is up"

# Verify the credentials yield a token. Retry: Wallabag can briefly 500 on the
# OAuth endpoint while warming up or during a concurrent redeploy, and a single
# transient failure must not hard-block web startup (this service gates it).
code=000
for attempt in $(seq 1 8); do
  code=$(curl -sS -o /tmp/tok.json -w '%{http_code}' -X POST "${API}/oauth/v2/token" \
    -d "grant_type=password&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&username=${USER}&password=${PASS}" || true)
  [ "${code}" = "200" ] && break
  log "token grant attempt ${attempt} returned HTTP ${code}; retrying ..."
  sleep 3
done
if [ "${code}" != "200" ]; then
  log "ERROR: token grant failed (HTTP ${code}) after retries — check WALLABAG_CLIENT_* + demo user"; cat /tmp/tok.json; exit 1
fi
log "verified password grant"

mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
# Generated by demo/wallabag/bootstrap.sh — do not edit by hand.
Skills__Wallabag__BaseUrl=${API}
Skills__Wallabag__ClientId=${CLIENT_ID}
Skills__Wallabag__ClientSecret=${CLIENT_SECRET}
Skills__Wallabag__Username=${USER}
Skills__Wallabag__Password=${PASS}
WALLABAG_API_URL=${API}
WALLABAG_CLIENT_ID=${CLIENT_ID}
WALLABAG_CLIENT_SECRET=${CLIENT_SECRET}
WALLABAG_USER=${USER}
WALLABAG_PASSWORD=${PASS}
EOF
log "wrote ${OUT}"
log "done"
