using FlowHub.Core.Captures;
using FlowHub.Core.Events;
using MassTransit;

namespace FlowHub.Persistence;

public sealed class EfCaptureService : ICaptureService
{
    private readonly ICaptureRepository _repository;
    private readonly IPublishEndpoint _publishEndpoint;

    public EfCaptureService(
        ICaptureRepository repository,
        IPublishEndpoint publishEndpoint)
    {
        _repository = repository;
        _publishEndpoint = publishEndpoint;
    }

    public Task<Capture?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default) =>
        _repository.GetByIdAsync(id, cancellationToken);

    public Task<IReadOnlyList<Capture>> GetAllAsync(CancellationToken cancellationToken = default) =>
        _repository.GetAllAsync(cancellationToken);

    public Task<IReadOnlyList<Capture>> GetRecentAsync(int count, CancellationToken cancellationToken = default) =>
        _repository.GetRecentAsync(count, cancellationToken);

    public Task<FailureCounts> GetFailureCountsAsync(CancellationToken cancellationToken = default) =>
        _repository.GetFailureCountsAsync(cancellationToken);

    public async Task<Capture> SubmitAsync(
        string content, ChannelKind source, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content);
        var capture = new Capture(Guid.NewGuid(), source, content, DateTimeOffset.UtcNow, LifecycleStage.Raw, null);
        var saved = await _repository.AddAsync(capture, cancellationToken);
        // Embedding is generated by CaptureEmbeddingConsumer off the request path (NF-09).
        await _publishEndpoint.Publish(
            new CaptureCreated(saved.Id, saved.Content, saved.Source, saved.CreatedAt),
            cancellationToken);
        return saved;
    }

    public async Task<Capture> SubmitAsync(
        string? content, ChannelKind source, AttachmentInput? attachment, CancellationToken cancellationToken = default)
    {
        if (attachment is null)
        {
            return await SubmitAsync(content ?? throw new ArgumentNullException(nameof(content)), source, cancellationToken);
        }

        throw new NotImplementedException("Attachment orchestration lands in Task 9.");
    }

    public async Task MarkClassifiedAsync(
        Guid id, string matchedSkill, string? title = null, string? vikunjaProject = null, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with
            {
                Stage = LifecycleStage.Classified,
                MatchedSkill = matchedSkill,
                Title = title ?? capture.Title,
                VikunjaProject = vikunjaProject ?? capture.VikunjaProject,
            },
            cancellationToken);
    }

    public async Task MarkRoutedAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(capture with { Stage = LifecycleStage.Routed }, cancellationToken);
    }

    public async Task MarkCompletedAsync(Guid id, string? externalRef, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Completed, ExternalRef = externalRef ?? capture.ExternalRef },
            cancellationToken);
    }

    public async Task MarkOrphanAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Orphan, FailureReason = reason },
            cancellationToken);
    }

    public async Task MarkUnhandledAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Unhandled, FailureReason = reason },
            cancellationToken);
    }

    public async Task ResetForRetryAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Raw, FailureReason = null },
            cancellationToken);
    }

    public Task<CapturePage> ListAsync(CaptureFilter filter, CancellationToken cancellationToken = default) =>
        _repository.ListAsync(filter, cancellationToken);
}
