using FlowHub.Core.Captures;
using FlowHub.Core.Events;
using MassTransit;

namespace FlowHub.Persistence;

public sealed class EfCaptureService : ICaptureService
{
    private readonly ICaptureRepository _repository;
    private readonly IPublishEndpoint _publishEndpoint;
    private readonly IAttachmentStorage _attachmentStorage;

    public EfCaptureService(
        ICaptureRepository repository,
        IPublishEndpoint publishEndpoint,
        IAttachmentStorage attachmentStorage)
    {
        _repository = repository;
        _publishEndpoint = publishEndpoint;
        _attachmentStorage = attachmentStorage;
    }

    public Task<Capture?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default) =>
        _repository.GetByIdAsync(id, cancellationToken);

    public Task<IReadOnlyList<Capture>> GetAllAsync(CancellationToken cancellationToken = default) =>
        _repository.GetAllAsync(cancellationToken);

    public Task<IReadOnlyList<Capture>> GetRecentAsync(int count, CancellationToken cancellationToken = default) =>
        _repository.GetRecentAsync(count, cancellationToken);

    public Task<FailureCounts> GetFailureCountsAsync(CancellationToken cancellationToken = default) =>
        _repository.GetFailureCountsAsync(cancellationToken);

    public async Task<Capture> SubmitAsync(
        string content, ChannelKind source, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content);
        var capture = new Capture(Guid.NewGuid(), source, content, DateTimeOffset.UtcNow, LifecycleStage.Raw, null);
        var saved = await _repository.AddAsync(capture, cancellationToken);
        // Embedding is generated by CaptureEmbeddingConsumer off the request path (NF-09).
        await _publishEndpoint.Publish(
            new CaptureCreated(saved.Id, saved.Content, saved.Source, saved.CreatedAt),
            cancellationToken);
        return saved;
    }

    public async Task<Capture> SubmitAsync(
        string? caption, ChannelKind source, AttachmentInput? attachment,
        bool needsTranscription = false, CancellationToken cancellationToken = default)
    {
        if (attachment is null)
        {
            var content = caption ?? throw new ArgumentNullException(nameof(caption));
            if (!needsTranscription)
            {
                return await SubmitAsync(content, source, cancellationToken);
            }

            // Validated like the sibling text overload: a blank placeholder would produce a
            // Capture with no content and nothing queued to replace it.
            ArgumentException.ThrowIfNullOrWhiteSpace(content);

            // Voice memo whose audio the handler chose not to download: the transcription
            // consumer fetches the audio from Telegram and calls SetTranscriptAsync.
            var textOnly = new Capture(
                Guid.NewGuid(), source, content, DateTimeOffset.UtcNow, LifecycleStage.Raw, null);
            var storedTextOnly = await _repository.AddAsync(textOnly, cancellationToken);
            await _publishEndpoint.Publish(
                new CaptureCreated(
                    storedTextOnly.Id, storedTextOnly.Content, storedTextOnly.Source, storedTextOnly.CreatedAt,
                    HasAttachment: false, NeedsTranscription: true),
                cancellationToken);
            return storedTextOnly;
        }

        var fileName = Path.GetFileName(attachment.FileName);
        var relativePath = await _attachmentStorage.SaveAsync(
            attachment.Content, fileName, attachment.ContentType, cancellationToken);

        var att = new Attachment(fileName, attachment.ContentType, attachment.SizeBytes, relativePath, DateTimeOffset.UtcNow);

        // The caption is the note; the file is the evidence. The filename is not lost —
        // it lives on the Attachment above, so this replaces a duplicated value rather
        // than displacing one. Content is what the classifier and the embedder read.
        // Whitespace-only counts as absent so a stray space cannot blank a Capture.
        var attContent = string.IsNullOrWhiteSpace(caption) ? fileName : caption.Trim();

        var capture = new Capture(
            Guid.NewGuid(), source, attContent, DateTimeOffset.UtcNow,
            LifecycleStage.Raw, MatchedSkill: null, Attachment: att);

        try
        {
            var saved = await _repository.AddAsync(capture, cancellationToken);
            await _publishEndpoint.Publish(
                new CaptureCreated(
                    saved.Id, saved.Content, saved.Source, saved.CreatedAt,
                    HasAttachment: true, NeedsTranscription: needsTranscription),
                cancellationToken);
            return saved;
        }
        catch
        {
            await _attachmentStorage.DeleteAsync(relativePath, CancellationToken.None);
            throw;
        }
    }

    public async Task<Capture> SetTranscriptAsync(Guid id, string transcript, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(transcript);
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        var updated = capture with { Content = transcript };
        await _repository.UpdateAsync(updated, cancellationToken);
        return updated;
    }

    public async Task MarkClassifiedAsync(
        Guid id, string matchedSkill, string? title = null, string? vikunjaProject = null, string? enrichmentDescription = null, FlowHub.Core.Classification.ClassifierTrace? trace = null, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with
            {
                Stage = LifecycleStage.Classified,
                MatchedSkill = matchedSkill,
                Title = title ?? capture.Title,
                VikunjaProject = vikunjaProject ?? capture.VikunjaProject,
                EnrichmentDescription = enrichmentDescription ?? capture.EnrichmentDescription,
                ClassifierTrace = trace ?? capture.ClassifierTrace,
            },
            cancellationToken);
    }

    public async Task MarkRoutedAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(capture with { Stage = LifecycleStage.Routed }, cancellationToken);
    }

    public async Task MarkCompletedAsync(Guid id, string? externalRef, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Completed, ExternalRef = externalRef ?? capture.ExternalRef },
            cancellationToken);
    }

    public async Task MarkOrphanAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Orphan, FailureReason = reason },
            cancellationToken);
    }

    public async Task MarkUnhandledAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Unhandled, FailureReason = reason },
            cancellationToken);
    }

    public async Task ResetForRetryAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var capture = await _repository.GetByIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException($"Capture {id} not found.");
        await _repository.UpdateAsync(
            capture with { Stage = LifecycleStage.Raw, FailureReason = null },
            cancellationToken);
    }

    public Task<CapturePage> ListAsync(CaptureFilter filter, CancellationToken cancellationToken = default) =>
        _repository.ListAsync(filter, cancellationToken);
}
