#!/usr/bin/env bash
# demo/paperless/bootstrap.sh — provision the demo paperless-ngx instance.
# Waits for the API, obtains an API token for the auto-created admin, and writes
# /bootstrap/paperless.env (sourced by flowhub.web to activate the Paperless skill
# and by the reset sidecar to clear documents each cycle).

set -euo pipefail

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { echo "[$(ts)] paperless-bootstrap: $*"; }

API="${PAPERLESS_API_URL:-http://paperless:8000}"
USER="${PAPERLESS_ADMIN_USER:-flowhub}"
PASS="${PAPERLESS_ADMIN_PASSWORD:-flowhub-demo}"
OUT="${BOOTSTRAP_OUT:-/bootstrap/paperless.env}"

log "waiting for ${API}/api/ ..."
ready=""
for _ in $(seq 1 120); do
  if curl -fsS "${API}/api/" >/dev/null 2>&1; then ready=1; break; fi
  sleep 3
done
[ -n "${ready}" ] || { log "ERROR: paperless did not become ready"; exit 1; }
log "paperless is up"

# Obtain an API token for the admin (auto-created via PAPERLESS_ADMIN_* on first boot).
TOKEN=$(curl -fsS -X POST "${API}/api/token/" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":\"${USER}\",\"password\":\"${PASS}\"}" | jq -r '.token // empty')
[ -n "${TOKEN}" ] || { log "ERROR: could not obtain API token"; exit 1; }
log "obtained API token"

mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
# Generated by demo/paperless/bootstrap.sh — do not edit by hand.
Skills__Paperless__BaseUrl=${API}
Skills__Paperless__ApiToken=${TOKEN}
PAPERLESS_API_URL=${API}
PAPERLESS_TOKEN=${TOKEN}
EOF
log "wrote ${OUT}"
log "done"
